### ISSUE TITLE
Float IC12 unused inputs

### ISSUE THREAD

**Issue by marmeladapk** [alice-fit-fee-upgrade/FIT_PM_Simulator#10]
(spi_mux)

> The DS90LV048A is a quad receiver device, and if an application requires only 1, 2 or 3
receivers, the unused channel(s) inputs should be left OPEN. Do not tie unused receiver inputs to ground or
any other voltages. The input is biased by internal high value pull up and pull down resistors to set the output
to a HIGH state. This internal circuitry will ensure a HIGH, stable output state for open inputs.

**Comment by gkasprow** [comment]
it's correct. The note applies to LVDS inputs of IC9

**Comment by marmeladapk** [comment]
That's a typo in the datasheet. It's taken from DS90LV047ATM/NOPB datasheet. It applies to IC12.

This is taken from 
https://www.ti.com/lit/ds/symlink/ds90lv047a.pdf

**Comment by gkasprow** [comment]
It doesn't make any sense. It's LVCMOS input and it cannot be left floatng. They just copied it from 048 chip. that's why they mention pullup and pull down resistors.
