### ISSUE TITLE
Wrong P3V3 voltage

### ISSUE THREAD

**Issue by marmeladapk** [alice-fit-fee-upgrade/FIT_PM_Simulator#6]
FB pin is regulated to 0,7 V not to 0,8 V.

**Comment by marmeladapk** [comment]
Datasheet recommends 560k and 150k for 3,3V.

**Comment by gkasprow** [comment]
![obraz](https://github.com/user-attachments/assets/ef4b7f3c-88b2-4dc7-a433-b0b34fb83b78)
